### ISSUE TITLE
make：*** modules ERROR 2

### ISSUE THREAD

**Issue by MIngPAPA** [masterzorag/RTL8192EU-linux#3]
Hello,
I'm working under openSUSE leap 42.1.The kernel version is 4.1.12-1.When compiling,I meet some problems.

make[1]: Entering directory '/lib/modules/4.1.12-1-default/build'
make[1]:*** No rules to make target 'modules'.Stop
make[1]:Leaving directory  '/lib/modules/4.1.12-1-default/build'
Makefile:1686 recipe for target 'modules' failed
make: ***[modules] Error :2

Thanks

**Comment by masterzorag** [comment]
It should works, the sequence should be:
```sh
make
make install
```
no _modules_ target in the Makefile

**Comment by masterzorag** [comment]
@MIngPAPA any update on the issue?

**Comment by MIngPAPA** [comment]
Sorry about the delay of reply.I just lent my device to my friend for a week.

Yes,your method is OK!
But, it is quite confused for me that I change my working environment  to Leap 42.2. After that, the building process is so frank. I don't know whether it should  blame to the former 42.1 or not.

At last, thanks for your attention and patience!

Best wishes.
